In [14]:
import numpy as np 

# Least-Squares via QR decomposition 

In [16]:
"""
Implementing the least-squares algorithm via QR decomposition. 
Comparing it with the method of computing the least-squares algo via the left inverse. 
Both outputs should be the same.
Proof is conducted using subtraction, taking one away from the other will give zero. 
Note: The proof is equal to 0 + computer rounding error. 
"""

# Generate random data (design matrix X, data y) 
m = 100
n = 6 
X = np.random.randn(m,n) 
y = np.random.randn(m,1) 

# Solve for beta using QR decomposition 
Q,R = np.linalg.qr(X,'complete')
beta_qr = np.linalg.solve(R.T@R, (Q@R).T@y)

# Compare QR results against the left inverse method 
beta_lstq = np.linalg.solve(X.T@X, X.T@y)
beta_lstq = np.linalg.lstsq(X,y,rcond=None)[0]

# Print 
print("Via QR Decomposition")
print(beta_qr)
print(" ")
print("Via the Left Inverse")
print(beta_lstq)
print(" ")
print("Proof")
print(beta_qr-beta_lstq)


Via QR Decomposition
[[-0.03711936]
 [-0.10251673]
 [ 0.01377047]
 [ 0.06995051]
 [ 0.05964589]
 [ 0.06797871]]
 
Via the Left Inverse
[[-0.03711936]
 [-0.10251673]
 [ 0.01377047]
 [ 0.06995051]
 [ 0.05964589]
 [ 0.06797871]]
 
Proof
[[-2.08166817e-17]
 [-5.55111512e-17]
 [-3.46944695e-17]
 [ 4.16333634e-17]
 [ 1.38777878e-17]
 [ 1.38777878e-17]]
